### ISSUE TITLE
spider bug on moving platforms

### ISSUE THREAD

**Issue by NaRKlz** [theyareonit/Click-Between-Frames#33] opened 2024-06-24 20:49 UTC
the spider will bounce off the moving platform when it lands on it 0:06, if you disable the mod the bug goes away 0:54
https://www.youtube.com/watch?v=G4DLh9_nBHI

**Comment by CuteistFox** [comment] 2024-06-24 22:22
dupe of #32

**Comment by theyareonit** [comment] 2024-07-06 15:26
should be fixed in v1.1.16

**Closed by theyareonit** 2024-07-06 15:26 UTC
