### ISSUE TITLE
can't run linux-input.exe.so

### ISSUE THREAD

**Issue by vulam49** [theyareonit/Click-Between-Frames#72] opened 2024-10-08 13:03 UTC
So when i tried to run GD with CBF i can't jump so i go into the issues page to check i search linux then it got me a tons of options but none of them work so i tried to run it in the terminal and after that i think for a while and then tried to follow the directory and i find a file call:"linux-input.exe.so". So i run it in terminal and it give me this error:

wine: failed to start L"Z:\\home\\vulam48\\Documents\\Geometry Dash\\geode\\unzipped\\syzzi.click_between_frames\\resources\\syzzi.click_between_frames\\linux-input.exe.so"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.
that all i could say

info:
os: Ubuntu 22.04
desktop: Gnome

**Comment by theyareonit** [comment] 2024-10-09 00:17
Yeah, it seems like it's broken on Debian based distros atm. Not really sure what the cause is, but try using a newer Wine/Proton version if possible.

Also, this is a duplicate of https://github.com/theyareonit/Click-Between-Frames/issues/68

**Closed by theyareonit** 2024-10-09 00:17 UTC

**Comment by vulam49** [comment] 2024-10-09 00:48
The fact that i already use the latest wine

**Comment by theyareonit** [comment] 2024-10-09 04:39
Which version specifically, though?

**Comment by vulam49** [comment] 2024-10-12 05:50
wine 9.19 (Development branch)

**Comment by vulam49** [comment] 2024-10-22 10:26
hey, any update man. I remenber that when I using Kubuntu It works but normal Ubuntu does not work.

**Comment by theyareonit** [comment] 2024-10-22 10:56
> I remenber that when I using Kubuntu It works but normal Ubuntu does not work.

That's odd. I'll probably test in an Ubuntu VM soon and see if I can figure it out, I've been quite busy with university lately so I haven't been able to work on the mod.
