### ISSUE TITLE
Hot rod bugs out with CBF on (upwards moving platform)

### ISSUE THREAD

**Issue by smooshymemes** [theyareonit/Click-Between-Frames#62] opened 2024-09-15 03:26 UTC
Please watch this video of the bug that I made, I can't describe it fully here
https://youtu.be/HzPorWaz8Kc
you fall much faster than normal off of the platform with cbf on, and it makes the orb after basically impossible
it's possible to do the click, but it's such a difficulty spike that it makes the entire level bad with cbf
I only pinned down that the cause was CBF today when I turned it off to play one of my own levels, then forgot to turn it back on and played hot rod, finding the bug was magically fixed (it had been bothering me for months at this point; the click just stopped working at some point)

no clue why this happens, but my guess is that it has something to do with the changes you made to moving platform velocity in v1.1.16

I have no idea how to recreate this bug, or the conditions required to see it, but hot rod seems to be broken so I'll leave it at that

**Comment by theyareonit** [comment] 2024-09-22 19:16
duplicate of https://github.com/theyareonit/Click-Between-Frames/issues/55

**Closed by theyareonit** 2024-09-22 19:16 UTC
